# Generated by Django 6.0.6 on 2026-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="traintype",
            options={"ordering": ["name"]},
        ),
    ]
