# Generated by Django 6.0.6 on 2026-06-07 16:46

import trains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0002_alter_train_options_alter_traintype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=trains.models.create_custom_path
            ),
        ),
    ]
