# Generated by Django 6.0.6 on 2026-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
    ]
