# Generated by Django 6.0.6 on 2026-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="trip",
            options={"ordering": ["-departure_time"]},
        ),
    ]
